# Generated by Django 6.0.4 on 2026-04-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_symptom_weight_dm_symptom_weight_htn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension_risk', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Gipertoniya xavfi (%)')),
                ('diabetes_risk', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diabet xavfi (%)')),
                ('clinical_alert', models.TextField(verbose_name='Kognitiv tavsiya')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction', to='patients.visit', verbose_name='Tashrif')),
            ],
        ),
    ]
