# Generated by Django 6.0.4 on 2026-04-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiyasi')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Otasining ismi')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Qabul vaqti')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tana harorati')),
                ('blood_pressure', models.CharField(max_length=15, verbose_name='Qon bosimi')),
                ('heart_rate', models.IntegerField(verbose_name='Yurak urishi')),
                ('symptoms', models.TextField(verbose_name='Simptomlar')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Bemor')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50, verbose_name='Tahlil turi')),
                ('file_path', models.URLField(max_length=500, verbose_name='PDF fayl manzili (URL)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.visit', verbose_name='Tashrif')),
            ],
        ),
    ]
