# Generated by Django 6.0.4 on 2026-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='file_path',
        ),
        migrations.AddField(
            model_name='labresult',
            name='file',
            field=models.FileField(default=0, upload_to='lab_results_pdfs/', verbose_name='PDF fayl yuklash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_type',
            field=models.CharField(choices=[('qon', 'Qon tahlili'), ('peshob', 'Peshob (Siydik) tahlili'), ('rentgen', 'Rentgen / MRT xulosasi'), ('boshqa', 'Boshqa tahlillar')], max_length=50, verbose_name='Tahlil turi'),
        ),
    ]
