# Generated by Django 6.0.4 on 2026-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_labresult_file_path_labresult_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='visit',
            name='arterial_pressure',
            field=models.CharField(default=0, max_length=15, verbose_name='Arterial qon bosimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='venous_pressure',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Vena qon bosimi'),
        ),
    ]
