# Generated by Django 6.0.4 on 2026-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_visit_blood_pressure_visit_arterial_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name="Tana bo'yi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tana massasi'),
            preserve_default=False,
        ),
    ]
