# Generated by Django 6.0.4 on 2026-04-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visit_height_visit_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Simptom nomi (O'zbekcha)")),
                ('code_name', models.CharField(max_length=50, unique=True, verbose_name='Tibbiy kodi (AI uchun)')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tana massasi indeksi (BMI)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Shifokor xulosasi / Qo'shimcha izoh"),
        ),
        migrations.AlterField(
            model_name='visit',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Bo'yi (sm)"),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='symptoms',
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vazni (kg)'),
        ),
        migrations.CreateModel(
            name='VisitSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Yengil (Kuchsiz)'), (2, "O'rtacha"), (3, "Og'ir (Kuchli)")], default=2, verbose_name='Darajasi')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.symptom', verbose_name='Simptom')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
            options={
                'unique_together': {('visit', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms',
            field=models.ManyToManyField(related_name='visits', through='patients.VisitSymptom', to='patients.symptom', verbose_name='Simptomlar'),
        ),
    ]
