# Generated by Django 6.0.4 on 2026-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_symptom_visit_bmi_visit_doctor_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='weight_dm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='DM (Diabet) vazni'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='weight_htn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='HTN (Gipertoniya) vazni'),
        ),
    ]
