# Generated by Django 6.0.4 on 2026-04-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_symptom_weight_dm_symptom_weight_htn'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='extracted_text',
            field=models.TextField(blank=True, null=True, verbose_name="O'qib olingan to'liq matn"),
        ),
        migrations.AddField(
            model_name='labresult',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Qand miqdori (mmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='leukocytes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Leykotsitlar'),
        ),
    ]
