# Generated by Django 6.0.4 on 2026-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_labresult_extracted_text_labresult_glucose_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='glucose_level',
        ),
        migrations.AddField(
            model_name='labresult',
            name='erythrocytes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eritrotsitlar (RBC)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gemoglobin (HB)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='platelets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Trombotsitlar (PLT)'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='leukocytes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Leykotsitlar (WBC)'),
        ),
    ]
