# Generated by Django 6.0.4 on 2026-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_labresult_glucose_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitsymptom',
            name='severity',
            field=models.DecimalField(choices=[(-1.0, 'Juda kuchli salbiy taʼsir (V1)'), (-0.75, 'Kuchli salbiy taʼsir (V2)'), (-0.5, 'O‘rtacha salbiy taʼsir (V3)'), (-0.25, 'Zaif salbiy taʼsir (V4)'), (0.0, 'Taʼsir yo‘q (V5)'), (0.25, 'Taʼsir kuchsiz (V6)'), (0.5, 'O‘rtacha taʼsir (V7)'), (0.75, 'Taʼsiri kuchli (V8)'), (1.0, 'Taʼsiri juda kuchli (V9)')], decimal_places=2, default=0.5, max_digits=3, verbose_name='Bemordagi darajasi'),
        ),
    ]
