# Generated by Django 6.0.4 on 2026-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_visit_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='arterial_pressure',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='venous_pressure',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='visit',
            name='blood_pressure',
            field=models.CharField(blank=True, default='120/80', max_length=20, null=True, verbose_name='Qon bosimi'),
        ),
    ]
