# Generated by Django 6.0.4 on 2026-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_visit_arterial_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsymptom',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitsymptom',
            name='severity',
            field=models.DecimalField(choices=[(0.0, 'Taʼsir yo‘q '), (0.25, 'Taʼsir kuchsiz '), (0.5, 'O‘rtacha taʼsir '), (0.75, 'Taʼsiri kuchli '), (1.0, 'Taʼsiri juda kuchli')], decimal_places=2, default=0.5, max_digits=3, verbose_name='Bemordagi darajasi'),
        ),
    ]
