# Generated by Django 6.0.4 on 2026-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_visitsymptom_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsymptom',
            name='dm_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitsymptom',
            name='htn_risk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
