# Generated by Django 6.0.4 on 2026-04-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_visitsymptom_dm_risk_visitsymptom_htn_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsymptom',
            name='doctor_feedback',
            field=models.CharField(blank=True, choices=[('alo', "A'lo"), ('yaxshi', 'Yaxshi'), ('qoniqarli', 'Qoniqarli'), ('yomon', 'Yomon')], max_length=20, null=True),
        ),
    ]
